;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ignore
	meow-append
	meow-cancel-selection
	meow-insert
	meow-insert-exit
	meow-next
	meow-prev
	meow-undo
	))

(setq mc/cmds-to-run-once
      '(
	))
